version: "3" # 파일 규격 버전
services:
    web:
        build:
            context: . #./app
            dockerfile: Dockerfile
            container_name: flack
            args:
                env: "development"
        ports:
            - "5000:5000" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
        volumes:
            - .:/app
