version: "2" # 파일 규격 버전
services: #이 항목 밑에 실행하려는 컨테이너 들을 정의
  apache: # 서비스 명
    image: httpd # 사용할 이미지
    restart: always # container를 실행할 때 항상 이미 수행중이라면 재시작을 수행합니다.
    container_name: apache # 컨테이너 이름 설정
    ports:
      #- "80:80" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
      - "8080:8080" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    volumes:
      #- /Users/yongsoo/apache2/htdocs:/usr/local/apache2/htdocs # -v 옵션 (다렉토리 마운트 설정)
      - /Users/yongsoo/apache2:/usr/local/apache2 #mac 
      #- /Users/yongsoo/apache2/conf/workers.properties:/usr/local/apache2/conf/workers.properties  #mac 파일이 없으면 디렉토리로 인식해서 에러 발생

#1. 볼륨 마운트 하지 않고 우선 컨테이너 실행 후 apache2 폴더 데이터를 호스트 컴퓨터 폴더에 복사.
#docker cp apache:/usr/local/apache2/ /Users/yongsoo/
#2. 설정 파일 수정 후 기존 컨테이너 삭제 및 볼륨 설정 후 다시 컨테이너 생성 하면 됨