version: "3" # 파일 규격 버전
services: #이 항목 밑에 실행하려는 컨테이너 들을 정의
  db: # 서비스 명
    image: mysql:8.0.23 # 사용할 이미지
    container_name: mysql8023 # 컨테이너 이름 설정
    ports:
      - "3306:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    environment: # -e 옵션
      MYSQL_ROOT_PASSWORD: "123456"  # MYSQL 패스워드 설정 옵션
    command: # 명령어 실행
      - --character-set-server=utf8mb4 #한글깨짐 방지
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /Users/yongsoo/dbdata/mysql_data:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)
      #- /home/dbdata/mysql_data:/var/lib/mysql #ubuntu
      #- /home/dockerhome/mysql/etc/my.cnf:/etc/my.cnf  #ubuntu
