version: "3.0" # 파일 규격 버전
services: #이 항목 밑에 실행하려는 컨테이너 들을 정의
  db: # 서비스 명
    image: postgres:13 # 사용할 이미지
    container_name: pgsql13 # 컨테이너 이름 설정
    ports:
      - "5432:5432" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    environment: # -e 옵션
      POSTGRES_PASSWORD: "123456"  # 패스워드 설정 옵션
      PGDATA: "/var/lib/postgresql/data/pgdata"
      #POSTGRES_INITDB_ARGS: " — data-checksums -E utf8 — no-locale" 
    volumes:
      - /Users/yongsoo/dbdata/pgsql_data:/var/lib/postgresql/data # -v 옵션 (다렉토리 마운트 설정)