version: "3.8"
services:
  node:
    image: "node:latest"
    container_name: "node"
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    #  - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: > 
        bash -c "npm install && npm start"